const pokemonSV =[
	{"dexId":"1", "name":"Sprigatito", "findable":false, "exclusive":false},
	{"dexId":"2", "name":"Floragato", "findable":false, "exclusive":false},
	{"dexId":"3", "name":"Meowscarada", "findable":false, "exclusive":false},
	{"dexId":"4", "name":"Fuecoco", "findable":false, "exclusive":false},
	{"dexId":"5", "name":"Crocalor", "findable":false, "exclusive":false},
	{"dexId":"6", "name":"Skeledirge", "findable":false, "exclusive":false},
	{"dexId":"7", "name":"Quaxly", "findable":false, "exclusive":false},
	{"dexId":"8", "name":"Quaxwell", "findable":false, "exclusive":false},
	{"dexId":"9", "name":"Quaquaval", "findable":false, "exclusive":false},
	{"dexId":"10", "name":"Lechonk", "findable":true, "exclusive":false},
	{"dexId":"11", "name":"Oinkologne", "findable":true, "exclusive":false},
	{"dexId":"12", "name":"Tarountula", "findable":true, "exclusive":false},
	{"dexId":"13", "name":"Spidops", "findable":true, "exclusive":false},
	{"dexId":"14", "name":"Nymble", "findable":true, "exclusive":false},
	{"dexId":"15", "name":"Lokix", "findable":true, "exclusive":false},
	{"dexId":"16", "name":"Hoppip", "findable":true, "exclusive":false},
	{"dexId":"17", "name":"Skipbloom", "findable":true, "exclusive":false},
	{"dexId":"18", "name":"Jumpluff", "findable":false, "exclusive":false},
	{"dexId":"19", "name":"Fletchling", "findable":true, "exclusive":false},
	{"dexId":"20", "name":"Fletchinder", "findable":true, "exclusive":false},
	{"dexId":"21", "name":"Talonflame", "findable":true, "exclusive":false},
	{"dexId":"22", "name":"Pawmi", "findable":true, "exclusive":false},
	{"dexId":"23", "name":"Pawmo", "findable":true, "exclusive":false},
	{"dexId":"24", "name":"Pawmot", "findable":false, "exclusive":false},
	{"dexId":"25", "name":"Houndoor", "findable":true, "exclusive":false},
	{"dexId":"26", "name":"Houndoom", "findable":true, "exclusive":false},
	{"dexId":"27", "name":"Yungoos", "findable":true, "exclusive":false},
	{"dexId":"28", "name":"Gumshoos", "findable":true, "exclusive":false},
	{"dexId":"29", "name":"Skwovet", "findable":true, "exclusive":false},
	{"dexId":"30", "name":"Greedent", "findable":true, "exclusive":false},
	{"dexId":"31", "name":"Sunkern", "findable":true, "exclusive":false},
	{"dexId":"32", "name":"Sunflora", "findable":true, "exclusive":true},
	{"dexId":"33", "name":"Kricketot", "findable":true, "exclusive":false},
	{"dexId":"34", "name":"Kricketune", "findable":true, "exclusive":false},
	{"dexId":"35", "name":"Scatterbug", "findable":true, "exclusive":false},
	{"dexId":"36", "name":"Spewpa", "findable":true, "exclusive":false},
	{"dexId":"37", "name":"Vivillon", "findable":true, "exclusive":false},
	{"dexId":"38", "name":"Combee", "findable":true, "exclusive":false},
	{"dexId":"39", "name":"Vespiquen", "findable":true, "exclusive":false},
	{"dexId":"40", "name":"Rookidee", "findable":true, "exclusive":false},
	{"dexId":"41", "name":"Corvisquire", "findable":true, "exclusive":false},
	{"dexId":"42", "name":"Corviknight", "findable":true, "exclusive":false},
	{"dexId":"43", "name":"Happiny", "findable":true, "exclusive":false},
	{"dexId":"44", "name":"Chansey", "findable":true, "exclusive":false},
	{"dexId":"45", "name":"Blissey", "findable":true, "exclusive":false},
	{"dexId":"46", "name":"Azurill", "findable":true, "exclusive":false},
	{"dexId":"47", "name":"Marill", "findable":true, "exclusive":false},
	{"dexId":"48", "name":"Azumarill", "findable":true, "exclusive":false},
	{"dexId":"49", "name":"Surskit", "findable":true, "exclusive":false},
	{"dexId":"50", "name":"Masquerain", "findable":true, "exclusive":false},
	{"dexId":"51", "name":"Buizel", "findable":true, "exclusive":false},
	{"dexId":"52", "name":"Floatzel", "findable":true, "exclusive":false},
	{"dexId":"53", "name":"Wooper", "findable":true, "exclusive":false},
	{"dexId":"54", "name":"Clodsire", "findable":true, "exclusive":false},
	{"dexId":"55", "name":"Psyduck", "findable":true, "exclusive":false},
	{"dexId":"56", "name":"Golduck", "findable":true, "exclusive":false},
	{"dexId":"57", "name":"Chewtle", "findable":true, "exclusive":false},
	{"dexId":"58", "name":"Drednaw", "findable":true, "exclusive":false},
	{"dexId":"59", "name":"Igglybuff", "findable":true, "exclusive":false},
	{"dexId":"60", "name":"Jigglypuff", "findable":true, "exclusive":false},
	{"dexId":"61", "name":"Wigglytuff", "findable":true, "exclusive":false},
	{"dexId":"62", "name":"Ralts", "findable":true, "exclusive":false},
	{"dexId":"63", "name":"Kirlia", "findable":true, "exclusive":false},
	{"dexId":"64", "name":"Gardevoir", "findable":true, "exclusive":false},
	{"dexId":"65", "name":"Gallade", "findable":true, "exclusive":false},
	{"dexId":"66", "name":"Drowzee", "findable":true, "exclusive":false},
	{"dexId":"67", "name":"Hypno", "findable":true, "exclusive":false},
	{"dexId":"68", "name":"Gastly", "findable":true, "exclusive":false},
	{"dexId":"69", "name":"Haunter", "findable":true, "exclusive":false},
	{"dexId":"70", "name":"Gengar", "findable":false, "exclusive":false},
	{"dexId":"71", "name":"Tandemaus", "findable":true, "exclusive":false},
	{"dexId":"72", "name":"Maushold", "findable":false, "exclusive":false},
	{"dexId":"73", "name":"Pichu", "findable":true, "exclusive":false},
	{"dexId":"74", "name":"Pikachu", "findable":true, "exclusive":false},
	{"dexId":"75", "name":"Raichu", "findable":true, "exclusive":false},
	{"dexId":"76", "name":"Fidough", "findable":true, "exclusive":false},
	{"dexId":"77", "name":"Dachsbun", "findable":true, "exclusive":false},
	{"dexId":"78", "name":"Slakoth", "findable":true, "exclusive":false},
	{"dexId":"79", "name":"Vigoroth", "findable":true, "exclusive":false},
	{"dexId":"80", "name":"Slaking", "findable":true, "exclusive":false},
	{"dexId":"81", "name":"Bounsweet", "findable":true, "exclusive":false},
	{"dexId":"82", "name":"Steenee", "findable":true, "exclusive":false},
	{"dexId":"83", "name":"Tsareena", "findable":false, "exclusive":false},
	{"dexId":"84", "name":"Smoliv", "findable":true, "exclusive":false},
	{"dexId":"85", "name":"Dolliv", "findable":true, "exclusive":false},
	{"dexId":"86", "name":"Arboliva", "findable":false, "exclusive":false},
	{"dexId":"87", "name":"Bonsly", "findable":true, "exclusive":false},
	{"dexId":"88", "name":"Sudowoodo", "findable":true, "exclusive":false},
	{"dexId":"89", "name":"Rockruff", "findable":true, "exclusive":false},
	{"dexId":"90", "name":"Lycanroc", "findable":true, "exclusive":false},
	{"dexId":"91", "name":"Rolycoly", "findable":true, "exclusive":false},
	{"dexId":"92", "name":"Carkol", "findable":true, "exclusive":false},
	{"dexId":"93", "name":"Coalossal", "findable":false, "exclusive":false},
	{"dexId":"94", "name":"Shinx", "findable":true, "exclusive":false},
	{"dexId":"95", "name":"Luxio", "findable":true, "exclusive":false},
	{"dexId":"96", "name":"Luxray", "findable":true, "exclusive":false},
	{"dexId":"97", "name":"Starly", "findable":true, "exclusive":false},
	{"dexId":"98", "name":"Staravia", "findable":true, "exclusive":false},
	{"dexId":"99", "name":"Staraptor", "findable":true, "exclusive":false},
	{"dexId":"100", "name":"Oricorio", "findable":true, "exclusive":false},
	{"dexId":"101", "name":"Mareep", "findable":true, "exclusive":false},
	{"dexId":"102", "name":"Flaaffy", "findable":true, "exclusive":false},
	{"dexId":"103", "name":"Ampharos", "findable":true, "exclusive":false},
	{"dexId":"104", "name":"Petilil", "findable":true, "exclusive":false},
	{"dexId":"105", "name":"Lilligant", "findable":true, "exclusive":false},
	{"dexId":"106", "name":"Shroomish", "findable":true, "exclusive":false},
	{"dexId":"107", "name":"Breloom", "findable":true, "exclusive":false},
	{"dexId":"108", "name":"Applin", "findable":true, "exclusive":false},
	{"dexId":"109", "name":"Flapple", "findable":false, "exclusive":false},
	{"dexId":"110", "name":"Appletun", "findable":false, "exclusive":false},
	{"dexId":"111", "name":"Spoink", "findable":true, "exclusive":false},
	{"dexId":"112", "name":"Grumpig", "findable":true, "exclusive":false},
	{"dexId":"113", "name":"Squawkabilly", "findable":true, "exclusive":false},
	{"dexId":"114", "name":"Misdreavus", "findable":true, "exclusive":false},
	{"dexId":"115", "name":"Mismagius", "findable":true, "exclusive":false},
	{"dexId":"116", "name":"Makuhita", "findable":true, "exclusive":false},
	{"dexId":"117", "name":"Hariyama", "findable":true, "exclusive":false},
	{"dexId":"118", "name":"Crabrawler", "findable":true, "exclusive":false},
	{"dexId":"119", "name":"Crabominable", "findable":true, "exclusive":false},
	{"dexId":"120", "name":"Salandit", "findable":true, "exclusive":false},
	{"dexId":"121", "name":"Salazzle", "findable":true, "exclusive":false},
	{"dexId":"122", "name":"Phanpy", "findable":true, "exclusive":false},
	{"dexId":"123", "name":"Donphan", "findable":true, "exclusive":false},
	{"dexId":"124", "name":"Cufant", "findable":true, "exclusive":false},
	{"dexId":"125", "name":"Copperajah", "findable":true, "exclusive":false},
	{"dexId":"126", "name":"Gible", "findable":true, "exclusive":false},
	{"dexId":"127", "name":"Gabite", "findable":true, "exclusive":false},
	{"dexId":"128", "name":"Garchomp", "findable":true, "exclusive":false},
	{"dexId":"129", "name":"Nacli", "findable":true, "exclusive":false},
	{"dexId":"130", "name":"Naclstack", "findable":true, "exclusive":false},
	{"dexId":"131", "name":"Garganacl", "findable":true, "exclusive":false},
	{"dexId":"132", "name":"Wingull", "findable":true, "exclusive":false},
	{"dexId":"133", "name":"Pelipper", "findable":true, "exclusive":false},
	{"dexId":"134", "name":"Magikarp", "findable":true, "exclusive":false},
	{"dexId":"135", "name":"Gyarados", "findable":true, "exclusive":false},
	{"dexId":"136", "name":"Arrokuda", "findable":true, "exclusive":false},
	{"dexId":"137", "name":"Barraskewda", "findable":true, "exclusive":false},
	{"dexId":"138", "name":"Basculin", "findable":false, "exclusive":false},
	{"dexId":"139", "name":"Gulpin", "findable":true, "exclusive":true},
	{"dexId":"140", "name":"Swalot", "findable":true, "exclusive":true},
	{"dexId":"141", "name":"Meowth", "findable":true, "exclusive":false},
	{"dexId":"142", "name":"Persian", "findable":true, "exclusive":false},
	{"dexId":"143", "name":"Drifloon", "findable":true, "exclusive":true},
	{"dexId":"144", "name":"Drifblim", "findable":true, "exclusive":true},
	{"dexId":"145", "name":"Flabébé", "findable":true, "exclusive":false},
	{"dexId":"146", "name":"Floette", "findable":true, "exclusive":false},
	{"dexId":"147", "name":"Florges", "findable":true, "exclusive":false},
	{"dexId":"148", "name":"Diglett", "findable":true, "exclusive":false},
	{"dexId":"149", "name":"Dugtrio", "findable":true, "exclusive":false},
	{"dexId":"150", "name":"Torkoal", "findable":true, "exclusive":false},
	{"dexId":"151", "name":"Numel", "findable":true, "exclusive":false},
	{"dexId":"152", "name":"Camerupt", "findable":true, "exclusive":false},
	{"dexId":"153", "name":"Bronzor", "findable":true, "exclusive":false},
	{"dexId":"154", "name":"Bronzong", "findable":true, "exclusive":false},
	{"dexId":"155", "name":"Axew", "findable":true, "exclusive":false},
	{"dexId":"156", "name":"Fraxure", "findable":true, "exclusive":false},
	{"dexId":"157", "name":"Haxorus", "findable":false, "exclusive":false},
	{"dexId":"158", "name":"Mankey", "findable":true, "exclusive":false},
	{"dexId":"159", "name":"Primeape", "findable":true, "exclusive":false},
	{"dexId":"160", "name":"Annihilape", "findable":false, "exclusive":false},
	{"dexId":"161", "name":"Meditite", "findable":true, "exclusive":false},
	{"dexId":"162", "name":"Medicham", "findable":true, "exclusive":false},
	{"dexId":"163", "name":"Riolu", "findable":true, "exclusive":false},
	{"dexId":"164", "name":"Lucario", "findable":true, "exclusive":false},
	{"dexId":"165", "name":"Charcadet", "findable":true, "exclusive":false},
	{"dexId":"166", "name":"Armarouge", "findable":false, "exclusive":true},
	{"dexId":"167", "name":"Ceruledge", "findable":false, "exclusive":true},
	{"dexId":"168", "name":"Barboach", "findable":true, "exclusive":false},
	{"dexId":"169", "name":"Whiscash", "findable":true, "exclusive":false},
	{"dexId":"170", "name":"Tadbulb", "findable":true, "exclusive":false},
	{"dexId":"171", "name":"Bellibolt", "findable":true, "exclusive":false},
	{"dexId":"172", "name":"Goomy", "findable":true, "exclusive":false},
	{"dexId":"173", "name":"Sliggoo", "findable":true, "exclusive":false},
	{"dexId":"174", "name":"Goodra", "findable":false, "exclusive":false},
	{"dexId":"175", "name":"Croagunk", "findable":true, "exclusive":false},
	{"dexId":"176", "name":"Toxicroak", "findable":true, "exclusive":false},
	{"dexId":"177", "name":"Wattrel", "findable":true, "exclusive":false},
	{"dexId":"178", "name":"Kilowattrel", "findable":true, "exclusive":false},
	{"dexId":"179", "name":"Eevee", "findable":true, "exclusive":false},
	{"dexId":"180", "name":"Vaporeon", "findable":true, "exclusive":false},
	{"dexId":"181", "name":"Jolteon", "findable":true, "exclusive":false},
	{"dexId":"182", "name":"Flareon", "findable":true, "exclusive":false},
	{"dexId":"183", "name":"Espeon", "findable":true, "exclusive":false},
	{"dexId":"184", "name":"Umbreon", "findable":true, "exclusive":false},
	{"dexId":"185", "name":"Leafeon", "findable":true, "exclusive":false},
	{"dexId":"186", "name":"Glaceon", "findable":true, "exclusive":false},
	{"dexId":"187", "name":"Sylveon", "findable":true, "exclusive":false},
	{"dexId":"188", "name":"Dunsparce", "findable":true, "exclusive":false},
	{"dexId":"189", "name":"Dudunsparce", "findable":true, "exclusive":false},
	{"dexId":"190", "name":"Deerling", "findable":true, "exclusive":false},
	{"dexId":"191", "name":"Sawsbuck", "findable":true, "exclusive":false},
	{"dexId":"192", "name":"Girafarig", "findable":true, "exclusive":false},
	{"dexId":"193", "name":"Farigiraf", "findable":true, "exclusive":false},
	{"dexId":"194", "name":"Grimer", "findable":true, "exclusive":false},
	{"dexId":"195", "name":"Muk", "findable":false, "exclusive":false},
	{"dexId":"196", "name":"Maschiff", "findable":true, "exclusive":false},
	{"dexId":"197", "name":"Mabosstiff", "findable":true, "exclusive":false},
	{"dexId":"198", "name":"Toxel", "findable":true, "exclusive":false},
	{"dexId":"199", "name":"Toxtricity", "findable":true, "exclusive":false},
	{"dexId":"200", "name":"Dedenne", "findable":true, "exclusive":false},
	{"dexId":"201", "name":"Pachirisu", "findable":true, "exclusive":false},
	{"dexId":"202", "name":"Shroodle", "findable":true, "exclusive":false},
	{"dexId":"203", "name":"Grafaiai", "findable":true, "exclusive":false},
	{"dexId":"204", "name":"Stantler", "findable":true, "exclusive":false},
	{"dexId":"205", "name":"Foongus", "findable":true, "exclusive":false},
	{"dexId":"206", "name":"Amoonguss", "findable":true, "exclusive":false},
	{"dexId":"207", "name":"Voltorb", "findable":true, "exclusive":false},
	{"dexId":"218", "name":"Electrode", "findable":true, "exclusive":false},
	{"dexId":"209", "name":"Magnemite", "findable":true, "exclusive":false},
	{"dexId":"210", "name":"Magneton", "findable":true, "exclusive":false},
	{"dexId":"211", "name":"Magnezone", "findable":true, "exclusive":false},
	{"dexId":"212", "name":"Ditto", "findable":true, "exclusive":false},
	{"dexId":"213", "name":"Growlithe", "findable":true, "exclusive":false},
	{"dexId":"214", "name":"Arcanine", "findable":true, "exclusive":false},
	{"dexId":"215", "name":"Teddiursa", "findable":true, "exclusive":false},
	{"dexId":"216", "name":"Ursaring", "findable":true, "exclusive":false},
	{"dexId":"217", "name":"Zangoose", "findable":true, "exclusive":false},
	{"dexId":"218", "name":"Seviper", "findable":true, "exclusive":false},
	{"dexId":"219", "name":"Swablu", "findable":true, "exclusive":false},
	{"dexId":"220", "name":"Altaria", "findable":true, "exclusive":false},
	{"dexId":"221", "name":"Skiddo", "findable":true, "exclusive":false},
	{"dexId":"222", "name":"Gogoat", "findable":true, "exclusive":false},
	{"dexId":"223", "name":"Tauros", "findable":true, "exclusive":false},
	{"dexId":"224", "name":"Litleo", "findable":true, "exclusive":false},
	{"dexId":"225", "name":"Pyroar", "findable":true, "exclusive":false},
	{"dexId":"226", "name":"Stunky", "findable":true, "exclusive":true},
	{"dexId":"227", "name":"Skuntank", "findable":true, "exclusive":true},
	{"dexId":"228", "name":"Zorua", "findable":true, "exclusive":false},
	{"dexId":"229", "name":"Zoroark", "findable":true, "exclusive":false},
	{"dexId":"230", "name":"Sneasel", "findable":true, "exclusive":false},
	{"dexId":"231", "name":"Weavile", "findable":true, "exclusive":false},
	{"dexId":"232", "name":"Murkrow", "findable":true, "exclusive":false},
	{"dexId":"233", "name":"Honchkrow", "findable":true, "exclusive":false},
	{"dexId":"234", "name":"Gothita", "findable":true, "exclusive":false},
	{"dexId":"235", "name":"Gothorita", "findable":true, "exclusive":false},
	{"dexId":"236", "name":"Gothitelle", "findable":true, "exclusive":false},
	{"dexId":"237", "name":"Sinistea", "findable":true, "exclusive":false},
	{"dexId":"238", "name":"Polteageist", "findable":false, "exclusive":false},
	{"dexId":"239", "name":"Mimikyu", "findable":true, "exclusive":false},
	{"dexId":"240", "name":"Klefki", "findable":true, "exclusive":false},
	{"dexId":"241", "name":"Indeedee", "findable":true, "exclusive":false},
	{"dexId":"242", "name":"Bramblin", "findable":true, "exclusive":false},
	{"dexId":"243", "name":"Brambleghast", "findable":true, "exclusive":false},
	{"dexId":"244", "name":"Toedscool", "findable":true, "exclusive":false},
	{"dexId":"245", "name":"Toedscruel", "findable":true, "exclusive":false},
	{"dexId":"246", "name":"Tropius", "findable":true, "exclusive":false},
	{"dexId":"247", "name":"Fomantis", "findable":true, "exclusive":false},
	{"dexId":"248", "name":"Lurantis", "findable":true, "exclusive":false},
	{"dexId":"249", "name":"Klawf", "findable":true, "exclusive":false},
	{"dexId":"250", "name":"Capsakid", "findable":true, "exclusive":false},
	{"dexId":"251", "name":"Scovillain", "findable":true, "exclusive":false},
	{"dexId":"252", "name":"Cacnea", "findable":true, "exclusive":false},
	{"dexId":"253", "name":"Cacturne", "findable":false, "exclusive":false},
	{"dexId":"254", "name":"Rellor", "findable":true, "exclusive":false},
	{"dexId":"255", "name":"Rabsca", "findable":false, "exclusive":false},
	{"dexId":"256", "name":"Venonat", "findable":true, "exclusive":false},
	{"dexId":"257", "name":"Venomoth", "findable":true, "exclusive":false},
	{"dexId":"258", "name":"Pineco", "findable":true, "exclusive":false},
	{"dexId":"259", "name":"Forretress", "findable":true, "exclusive":false},
	{"dexId":"260", "name":"Scyther", "findable":true, "exclusive":false},
	{"dexId":"261", "name":"Scizor", "findable":false, "exclusive":false},
	{"dexId":"262", "name":"Heracross", "findable":true, "exclusive":false},
	{"dexId":"263", "name":"Flittle", "findable":true, "exclusive":false},
	{"dexId":"264", "name":"Espathra", "findable":true, "exclusive":false},
	{"dexId":"265", "name":"Hippopotas", "findable":true, "exclusive":false},
	{"dexId":"266", "name":"Hippowdon", "findable":false, "exclusive":false},
	{"dexId":"267", "name":"Sandile", "findable":true, "exclusive":false},
	{"dexId":"268", "name":"Krokorok", "findable":false, "exclusive":false},
	{"dexId":"269", "name":"Krookodile", "findable":false, "exclusive":false},
	{"dexId":"270", "name":"Silicobra", "findable":true, "exclusive":false},
	{"dexId":"271", "name":"Sandaconda", "findable":false, "exclusive":false},
	{"dexId":"272", "name":"Mudbray", "findable":true, "exclusive":false},
	{"dexId":"273", "name":"Mudsdale", "findable":true, "exclusive":false},
	{"dexId":"274", "name":"Larvesta", "findable":true, "exclusive":false},
	{"dexId":"275", "name":"Volcarona", "findable":true, "exclusive":false},
	{"dexId":"276", "name":"Bagon", "findable":true, "exclusive":true},
	{"dexId":"277", "name":"Shelgon", "findable":true, "exclusive":true},
	{"dexId":"278", "name":"Salamence", "findable":true, "exclusive":true},
	{"dexId":"279", "name":"Tinkatink", "findable":true, "exclusive":false},
	{"dexId":"280", "name":"Tinkatuff", "findable":true, "exclusive":false},
	{"dexId":"281", "name":"Tinkaton", "findable":false, "exclusive":false},
	{"dexId":"282", "name":"Hatenna", "findable":true, "exclusive":false},
	{"dexId":"283", "name":"Hattrem", "findable":true, "exclusive":false},
	{"dexId":"284", "name":"Hatterene", "findable":false, "exclusive":false},
	{"dexId":"285", "name":"Impidimp", "findable":true, "exclusive":false},
	{"dexId":"286", "name":"Morgrem", "findable":true, "exclusive":false},
	{"dexId":"287", "name":"Grimmsnarl", "findable":false, "exclusive":false},
	{"dexId":"288", "name":"Wiglett", "findable":true, "exclusive":false},
	{"dexId":"289", "name":"Wugtrio", "findable":true, "exclusive":false},
	{"dexId":"290", "name":"Bombirdier", "findable":true, "exclusive":false},
	{"dexId":"291", "name":"Finizen", "findable":true, "exclusive":false},
	{"dexId":"292", "name":"Palafin", "findable":false, "exclusive":false},
	{"dexId":"293", "name":"Varoom", "findable":true, "exclusive":false},
	{"dexId":"294", "name":"Revavroom", "findable":true, "exclusive":false},
	{"dexId":"295", "name":"Cyclizar", "findable":true, "exclusive":false},
	{"dexId":"296", "name":"Orthworm", "findable":true, "exclusive":false},
	{"dexId":"297", "name":"Sableye", "findable":true, "exclusive":false},
	{"dexId":"298", "name":"Shuppet", "findable":true, "exclusive":false},
	{"dexId":"299", "name":"Banette", "findable":true, "exclusive":false},
	{"dexId":"300", "name":"Falinks", "findable":true, "exclusive":false},
	{"dexId":"301", "name":"Hawlucha", "findable":true, "exclusive":false},
	{"dexId":"302", "name":"Spiritomb", "findable":true, "exclusive":false},
	{"dexId":"303", "name":"Noibat", "findable":true, "exclusive":false},
	{"dexId":"304", "name":"Noivern", "findable":true, "exclusive":false},
	{"dexId":"305", "name":"Dreepy", "findable":true, "exclusive":false},
	{"dexId":"306", "name":"Drakloak", "findable":true, "exclusive":false},
	{"dexId":"307", "name":"Dragapult", "findable":false, "exclusive":true},
	{"dexId":"308", "name":"Glimmet", "findable":true, "exclusive":false},
	{"dexId":"309", "name":"Glimmora", "findable":true, "exclusive":false},
	{"dexId":"310", "name":"Rotom", "findable":true, "exclusive":false},
	{"dexId":"311", "name":"Greavard", "findable":true, "exclusive":false},
	{"dexId":"312", "name":"Houndstone", "findable":true, "exclusive":false},
	{"dexId":"313", "name":"Oranguru", "findable":true, "exclusive":true},
	{"dexId":"314", "name":"Passimian", "findable":true, "exclusive":true},
	{"dexId":"315", "name":"Komala", "findable":true, "exclusive":false},
	{"dexId":"316", "name":"Larvitar", "findable":true, "exclusive":true},
	{"dexId":"317", "name":"Pupitar", "findable":true, "exclusive":true},
	{"dexId":"318", "name":"Tyranitar", "findable":false, "exclusive":true},
	{"dexId":"319", "name":"Stonjourner", "findable":true, "exclusive":true},
	{"dexId":"320", "name":"Eiscue", "findable":true, "exclusive":true},
	{"dexId":"321", "name":"Pincurchin", "findable":true, "exclusive":false},
	{"dexId":"322", "name":"Sandygast", "findable":true, "exclusive":false},
	{"dexId":"323", "name":"Palossand", "findable":true, "exclusive":false},
	{"dexId":"324", "name":"Slowpoke", "findable":true, "exclusive":false},
	{"dexId":"325", "name":"Slowbro", "findable":true, "exclusive":false},
	{"dexId":"326", "name":"Slowking", "findable":false, "exclusive":false},
	{"dexId":"327", "name":"Shellos", "findable":true, "exclusive":false},
	{"dexId":"328", "name":"Gastrodon", "findable":true, "exclusive":false},
	{"dexId":"329", "name":"Shellder", "findable":true, "exclusive":false},
	{"dexId":"330", "name":"Cloyster", "findable":true, "exclusive":false},
	{"dexId":"331", "name":"Qwilfish", "findable":true, "exclusive":false},
	{"dexId":"332", "name":"Luvdisc", "findable":true, "exclusive":false},
	{"dexId":"333", "name":"Finneon", "findable":true, "exclusive":false},
	{"dexId":"334", "name":"Lumineon", "findable":true, "exclusive":false},
	{"dexId":"335", "name":"Bruxish", "findable":true, "exclusive":false},
	{"dexId":"336", "name":"Alomomola", "findable":true, "exclusive":false},
	{"dexId":"337", "name":"Skrelp", "findable":true, "exclusive":true},
	{"dexId":"338", "name":"Dragalge", "findable":true, "exclusive":true},
	{"dexId":"339", "name":"Clauncher", "findable":true, "exclusive":true},
	{"dexId":"340", "name":"Clawitzer", "findable":true, "exclusive":true},
	{"dexId":"341", "name":"Tynamo", "findable":true, "exclusive":false},
	{"dexId":"342", "name":"Eelektrik", "findable":true, "exclusive":false},
	{"dexId":"343", "name":"Eelektross", "findable":false, "exclusive":false},
	{"dexId":"344", "name":"Mareanie", "findable":true, "exclusive":false},
	{"dexId":"345", "name":"Toxapex", "findable":false, "exclusive":false},
	{"dexId":"346", "name":"Flamigo", "findable":true, "exclusive":false},
	{"dexId":"347", "name":"Dratini", "findable":true, "exclusive":false},
	{"dexId":"348", "name":"Dragonair", "findable":true, "exclusive":false},
	{"dexId":"349", "name":"Dragonite", "findable":true, "exclusive":false},
	{"dexId":"350", "name":"Snom", "findable":true, "exclusive":false},
	{"dexId":"351", "name":"Frosmoth", "findable":true, "exclusive":false},
	{"dexId":"352", "name":"Snover", "findable":true, "exclusive":false},
	{"dexId":"353", "name":"Abomasnow", "findable":true, "exclusive":false},
	{"dexId":"354", "name":"Delibird", "findable":true, "exclusive":false},
	{"dexId":"355", "name":"Cubchoo", "findable":true, "exclusive":false},
	{"dexId":"356", "name":"Beartic", "findable":true, "exclusive":false},
	{"dexId":"357", "name":"Snorunt", "findable":true, "exclusive":false},
	{"dexId":"358", "name":"Glalie", "findable":true, "exclusive":false},
	{"dexId":"359", "name":"Froslass", "findable":true, "exclusive":false},
	{"dexId":"360", "name":"Cryogonal", "findable":true, "exclusive":false},
	{"dexId":"361", "name":"Cetoddle", "findable":true, "exclusive":false},
	{"dexId":"362", "name":"Cetitan", "findable":true, "exclusive":false},
	{"dexId":"363", "name":"Bergmite", "findable":true, "exclusive":false},
	{"dexId":"364", "name":"Avalugg", "findable":true, "exclusive":false},
	{"dexId":"365", "name":"Rufflet", "findable":true, "exclusive":false},
	{"dexId":"366", "name":"Braviary", "findable":true, "exclusive":false},
	{"dexId":"367", "name":"Pawniard", "findable":true, "exclusive":false},
	{"dexId":"368", "name":"Bisharp", "findable":true, "exclusive":false},
	{"dexId":"369", "name":"Kingambit", "findable":false, "exclusive":false},
	{"dexId":"370", "name":"Deino", "findable":true, "exclusive":true},
	{"dexId":"371", "name":"Zweilous", "findable":true, "exclusive":true},
	{"dexId":"372", "name":"Hydreigon", "findable":false, "exclusive":true},
	{"dexId":"373", "name":"Veluza", "findable":true, "exclusive":false},
	{"dexId":"374", "name":"Dondozo", "findable":true, "exclusive":false},
	{"dexId":"375", "name":"Tatsugiri", "findable":true, "exclusive":false},
	{"dexId":"376", "name":"Great Tusk", "findable":true, "exclusive":true},
	{"dexId":"377", "name":"Scream Tail", "findable":true, "exclusive":true},
	{"dexId":"378", "name":"Brute Bonnet", "findable":true, "exclusive":true},
	{"dexId":"379", "name":"Flutter Mane", "findable":true, "exclusive":true},
	{"dexId":"380", "name":"Slither Wing", "findable":true, "exclusive":true},
	{"dexId":"381", "name":"Sandy Shocks", "findable":true, "exclusive":true},
	{"dexId":"382", "name":"Iron Treads", "findable":true, "exclusive":true},
	{"dexId":"383", "name":"Iron Bundle", "findable":true, "exclusive":true},
	{"dexId":"384", "name":"Iron Hands", "findable":true, "exclusive":true},
	{"dexId":"385", "name":"Iron Jugulis", "findable":true, "exclusive":true},
	{"dexId":"386", "name":"Iron Moth", "findable":true, "exclusive":true},
	{"dexId":"387", "name":"Iron Thorns", "findable":true, "exclusive":true},
	{"dexId":"388", "name":"Frigibax", "findable":true, "exclusive":false},
	{"dexId":"389", "name":"Arctibax", "findable":true, "exclusive":false},
	{"dexId":"390", "name":"Baxcalibur", "findable":false, "exclusive":false},
	{"dexId":"391", "name":"Gimmighoul", "findable":true, "exclusive":false},
	{"dexId":"392", "name":"Gholdengo", "findable":false, "exclusive":false},
	{"dexId":"393", "name":"Wo-Chien", "findable":false, "exclusive":false},
	{"dexId":"394", "name":"Chien-Pao", "findable":false, "exclusive":false},
	{"dexId":"395", "name":"Ting-Lu", "findable":false, "exclusive":false},
	{"dexId":"396", "name":"Chi-Yu", "findable":false, "exclusive":false},
	{"dexId":"397", "name":"Roaring Moon", "findable":true, "exclusive":true},
	{"dexId":"398", "name":"Iron Valiant", "findable":false, "exclusive":true},
	{"dexId":"399", "name":"Koraidon", "findable":false, "exclusive":true},
	{"dexId":"400", "name":"Miraidon", "findable":false, "exclusive":true}
	]
   
let clicker = document.getElementById("clickMe");
clicker.addEventListener("click", createEntries);
let flexBox = document.getElementsByClassName("flexbox")
// Defined in global so both functions can use
let chosenNumber;
let tempArrayChecker;
function createEntries(){	

	if(clicker.classList.contains("clickMeOriginal")){
		clicker.classList.remove("clickMeOriginal")
		clicker.classList.add("clickerNewLocation")
	}
	const tempArray = []
	
	// cleaning the current bingo list
	flexBox[0].innerHTML = ""
    for(let i = 0; i < 25;i++){
		//Create elements for each dexentry added to the bingo and attach them to the flexbox
		let div = document.createElement("div");
		div.setAttribute("class", "flexitem");
		if(i==0 || i==4 || i==20 || i==24){div.classList.add("corner"+i)}
        let dexAndName = document.createElement("p");
		let pokeImg = document.createElement("img");
        chosenNumber = getRandomNumber(0,399);	
		do{
			tempArrayChecker = 1
			tempArray.forEach(compareArray)
			if(pokemonSV[chosenNumber].exclusive == true){tempArrayChecker = 0}
			if(pokemonSV[chosenNumber].findable == false){tempArrayChecker = 0}
			if(tempArrayChecker == 0){chosenNumber = getRandomNumber(0,399)}
		 }while(tempArrayChecker == 0)
		tempArray.push(chosenNumber);
		pokeImg.setAttribute("src", "./assets/img/dexEntries/" + pokemonSV[chosenNumber].name + ".png")
		pokeImg.setAttribute("alt", "image of " + pokemonSV[chosenNumber].name)
        dexAndName.innerHTML = (chosenNumber+1) + " - " + pokemonSV[chosenNumber].name;
		div.appendChild(pokeImg);
		div.appendChild(dexAndName);
        flexBox[0].appendChild(div)
    }
}

function compareArray(value){if(value == chosenNumber){tempArrayChecker = 0}}

function getRandomNumber(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return parseInt(Math.floor(Math.random() * (max - min + 1) + min))
}

flexBox[0].addEventListener('click', (e) => {
	if(e.target.tagName == "DIV"){e.target.classList.toggle("cover")}
	else{console.log(e.target.parentElement.classList.toggle("cover"))}
})
